# Generated by Django 4.0.3 on 2022-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('type', models.IntegerField(verbose_name='Type')),
                ('episodes', models.IntegerField(verbose_name='Episodes')),
                ('curr_ep', models.IntegerField(verbose_name='Current Ep')),
                ('last_view', models.DateTimeField(auto_now=True, verbose_name='Last View')),
            ],
        ),
    ]
