# Generated by Django 4.0.3 on 2022-04-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='Movies',
        ),
    ]
