# Generated by Django 4.0.3 on 2022-04-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movies_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
    ]
